// ⚠️  NEW CHAT? READ /IOS_CONTINUITY.md AT REPO ROOT FIRST. Non-negotiable.
//     Working baseline tag on GitHub: ios-baseline-working (commit d7e7824)
//     styleWebViewForSafeArea() below is part of the strip fix — do not remove
//     without reading section 4 of IOS_CONTINUITY.md.

import UIKit
import Capacitor
import AVFoundation
import WebKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    // 120Hz ProMotion display link (iPhone 13 Pro and newer)
    private var displayLink: CADisplayLink?

    // ── AUDIO BELT-AND-SUSPENDERS STATE (v81 Build 4) ─────────────────────────
    // These pair with src/85-resume-gate.js v81 (window._jhResumeGate).
    //
    // Goal: silently recover the JS AudioContext after iOS suspends/interrupts
    // the WebView's audio session, without forcing the user to tap the overlay.
    //
    // Flow:
    //   1. iOS lifecycle/interruption fires → we reactivate AVAudioSession +
    //      call window._jhResumeGate.tryNativeResume() via evaluateJavaScript.
    //   2. WebKit treats evaluateJavaScript from a native lifecycle callback as
    //      a trusted-activation context on most iOS versions, so AudioContext
    //      .resume() inside tryNativeResume() succeeds without an overlay tap.
    //   3. If tryNativeResume() returns false, JS shows the v80 overlay as
    //      fallback — guaranteed gesture recovery from user tap.
    //
    // Reverse direction (JS → native):
    //   _nuclearRecover() in JS posts {action:'rebuildSession'} to
    //   webkit.messageHandlers.jhAudio at the top of the overlay-tap path.
    //   We rebuild the AVAudioSession synchronously enough that the subsequent
    //   JS resume() still rides the user gesture. Per web-chat spec: must be
    //   debounced (~500ms) because tryNativeResume + overlay-tap both call it
    //   within ~120ms in the failure path.
    private var _audioBridgeRegistered = false
    private var _lastSessionRebuildAt: TimeInterval = 0
    private static let JH_AUDIO_HANDLER_NAME = "jhAudio"
    private static let SESSION_REBUILD_DEBOUNCE: TimeInterval = 0.5
    // 0.05s silent 8kHz mono 8-bit PCM WAV, base64-encoded (444 bytes raw).
    // Played via AVAudioPlayer after each session rebuild to nudge iOS's audio
    // routing layer fully awake — same pattern as the JS silent-buffer kick,
    // but on the native side where AVAudioPlayer's lifecycle differs from
    // WebAudio's AudioBufferSourceNode.
    // Generated by: python3 -c 'see scripts comment' — 8000Hz, 400 samples, 0x80 silence bytes.
    private static let JH_NUDGE_WAV_B64 = "UklGRrQBAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YZABAACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
    private var _audioNudgePlayer: AVAudioPlayer?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // ── AUDIO ─────────────────────────────────────────────────────────────
        // .ambient = mixes with Spotify/Apple Music + respects silent switch.
        // We deliberately stay on .ambient (not .playback) — keeping silent-switch
        // honor and mix-with-others. The belt-and-suspenders for the swipe-away
        // bug is the observer + bridge stack below, NOT a category change.
        do {
            try AVAudioSession.sharedInstance().setCategory(
                .ambient,
                mode: .default,
                options: [.mixWithOthers]
            )
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            NSLog("[JetHorizon] AVAudioSession setup failed: \(error)")
        }

        // ── PREVENT IDLE/THROTTLE ─────────────────────────────────────────────
        // Stops iOS from dimming, sleeping, or down-clocking the GPU mid-play.
        application.isIdleTimerDisabled = true

        // ── 120Hz PROMOTION ───────────────────────────────────────────────────
        // Request the highest available refresh rate on ProMotion devices
        // (iPhone 13 Pro, 14 Pro, 15 Pro, 16 Pro). On non-ProMotion devices
        // this is a no-op — they stay at 60Hz.
        if #available(iOS 15.0, *) {
            let link = CADisplayLink(target: self, selector: #selector(displayTick))
            link.preferredFrameRateRange = CAFrameRateRange(minimum: 80, maximum: 120, preferred: 120)
            link.add(to: .main, forMode: .common)
            self.displayLink = link
        }

        // ── AUDIO INTERRUPTION OBSERVER (Build 4) ─────────────────────────────
        // Fires on phone calls, Siri, Control Center playback, etc. On .ended
        // we reactivate the session and call into JS to resume the AudioContext
        // from a trusted-activation context (avoids the overlay tap).
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleAudioInterruption(_:)),
            name: AVAudioSession.interruptionNotification,
            object: AVAudioSession.sharedInstance()
        )

        return true
    }

    // ── WEB INSPECTOR GATING ──────────────────────────────────────────────────
    // iOS 16.4+: WKWebView is only inspectable from Safari Web Inspector when
    // isInspectable=true. Default in CapacitorBridge is true in DEBUG builds,
    // but we want to be explicit: never inspectable in RELEASE so end users
    // cannot peek at the bundle from a tethered Mac. Hooks into Capacitor's
    // bridge after didFinishLaunching via applicationDidBecomeActive (the
    // earliest point where the bridge VC + webView are guaranteed to exist).
    private var _inspectorGated = false
    private func gateWebInspector() {
        if _inspectorGated { return }
        guard let bridgeVC = window?.rootViewController as? CAPBridgeViewController,
              let webView = bridgeVC.webView else { return }
        if #available(iOS 16.4, *) {
            #if DEBUG
            webView.isInspectable = true
            #else
            webView.isInspectable = false
            #endif
            _inspectorGated = true
        }
    }

    // ── WEBVIEW BACKGROUND / SAFE-AREA STRIP FIX ──────────────────────────────
    // Capacitor's `ios.backgroundColor` config is ignored because the WKWebView
    // is opaque by default (https://github.com/ionic-team/capacitor/issues/5335).
    // The opaque WebView paints its own system background (black) into the
    // safe-area gap below the home indicator, producing the visible black strip.
    //
    // Fix: make the WebView transparent so the underlying view's
    // backgroundColor (set from capacitor.config.json `backgroundColor`) shows
    // through, AND set the WebView's own backgroundColor to the page bg
    // (#050614) as belt-and-suspenders for the moments before WebKit paints
    // anything. This is the native equivalent of what mobile Safari does
    // automatically for PWAs — that's why the web build never shows the strip.
    //
    // Page bg = --color-bg in style.css = #050614 (deep dark blue).
    private var _webViewStyled = false
    private func styleWebViewForSafeArea() {
        if _webViewStyled { return }
        guard let bridgeVC = window?.rootViewController as? CAPBridgeViewController,
              let webView = bridgeVC.webView else { return }
        let pageBg = UIColor(red: 0x05/255.0, green: 0x06/255.0, blue: 0x14/255.0, alpha: 1.0)
        webView.isOpaque = false
        webView.backgroundColor = pageBg
        webView.scrollView.backgroundColor = pageBg
        bridgeVC.view.backgroundColor = pageBg
        if let win = window {
            win.backgroundColor = pageBg
        }
        _webViewStyled = true
    }

    // ── JS BRIDGE: register window.webkit.messageHandlers.jhAudio ─────────────
    // Called from applicationDidBecomeActive once the bridge VC + webView exist.
    // The handler is the AppDelegate itself (WKScriptMessageHandler extension
    // below). JS posts {action:'rebuildSession'} when it wants the native
    // AVAudioSession torn down + rebuilt; we debounce to 500ms because
    // tryNativeResume() and the overlay-tap fallback can fire within ~120ms.
    private func registerAudioBridge() {
        if _audioBridgeRegistered { return }
        guard let bridgeVC = window?.rootViewController as? CAPBridgeViewController,
              let webView = bridgeVC.webView else { return }
        webView.configuration.userContentController.add(self, name: AppDelegate.JH_AUDIO_HANDLER_NAME)
        _audioBridgeRegistered = true
    }

    // ── REBUILD AVAudioSession (called by jhAudio bridge + interruption.ended) ─
    // Tear down + re-create the session, then play a 0.05s silent buffer to
    // nudge iOS's audio routing layer fully awake. Debounced to 500ms per
    // web-chat spec (handler is called twice in the failure path).
    fileprivate func rebuildAudioSession(reason: String) {
        let now = Date.timeIntervalSinceReferenceDate
        if now - _lastSessionRebuildAt < AppDelegate.SESSION_REBUILD_DEBOUNCE {
            return // debounce — recent rebuild still warm
        }
        _lastSessionRebuildAt = now

        let session = AVAudioSession.sharedInstance()
        do {
            try session.setActive(false, options: [.notifyOthersOnDeactivation])
            try session.setCategory(.ambient, mode: .default, options: [.mixWithOthers])
            try session.setActive(true)
        } catch {
            NSLog("[JetHorizon] rebuildAudioSession(\(reason)) failed: \(error)")
            return
        }
        playSilentNudge()
    }

    // Plays the embedded 0.05s silent WAV via AVAudioPlayer. Releases the
    // previous player and re-creates each call so the player's lifecycle
    // stays clean across rebuilds.
    private func playSilentNudge() {
        guard let data = Data(base64Encoded: AppDelegate.JH_NUDGE_WAV_B64) else { return }
        do {
            _audioNudgePlayer = try AVAudioPlayer(data: data)
            _audioNudgePlayer?.volume = 0.0
            _audioNudgePlayer?.prepareToPlay()
            _audioNudgePlayer?.play()
        } catch {
            // Non-fatal — session rebuild is the primary mechanism.
            NSLog("[JetHorizon] silent nudge failed: \(error)")
        }
    }

    // ── JS bridge: call window._jhResumeGate.tryNativeResume() ────────────────
    // Invoked from applicationDidBecomeActive + interruption.ended. The
    // resume-gate (v81) returns true if AudioContext is running afterwards,
    // false if the overlay was shown as fallback. We don't need to act on the
    // result — it's logged for debugging only.
    private func invokeTryNativeResume(reason: String) {
        guard let bridgeVC = window?.rootViewController as? CAPBridgeViewController,
              let webView = bridgeVC.webView else { return }
        let js = """
        (function(){
          try {
            if (window._jhResumeGate && window._jhResumeGate.tryNativeResume) {
              return window._jhResumeGate.tryNativeResume();
            }
          } catch(e) { return false; }
          return false;
        })();
        """
        webView.evaluateJavaScript(js) { (result, error) in
            if let error = error {
                NSLog("[JetHorizon] tryNativeResume(\(reason)) eval error: \(error)")
            }
        }
    }

    // ── AVAudioSession.interruptionNotification handler ───────────────────────
    @objc private func handleAudioInterruption(_ notification: Notification) {
        guard let info = notification.userInfo,
              let typeRaw = info[AVAudioSessionInterruptionTypeKey] as? UInt,
              let type = AVAudioSession.InterruptionType(rawValue: typeRaw) else {
            return
        }
        switch type {
        case .began:
            // iOS is taking over audio (phone call, Siri, alarm, etc.).
            // Nothing to do here — JS will detect via visibilitychange/pagehide
            // and snapshot the playing tracks. Native session is auto-deactivated.
            NSLog("[JetHorizon] AVAudioSession interruption began")
        case .ended:
            // The interrupting event finished. Reactivate + nudge JS to resume.
            let shouldResume: Bool = {
                if let optsRaw = info[AVAudioSessionInterruptionOptionKey] as? UInt {
                    return AVAudioSession.InterruptionOptions(rawValue: optsRaw).contains(.shouldResume)
                }
                return true
            }()
            if !shouldResume { return }
            do {
                try AVAudioSession.sharedInstance().setActive(true)
            } catch {
                NSLog("[JetHorizon] reactivate after interruption failed: \(error)")
            }
            invokeTryNativeResume(reason: "interruption.ended")
        @unknown default:
            return
        }
    }

    @objc private func displayTick() {
        // No-op: just by existing this CADisplayLink tells the system the app
        // wants 120Hz, which lifts the WebView/CAMetalLayer cap.
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Pause every <audio> element synchronously the moment the user begins
        // swiping the app away (or any other resign-active gesture). Capacitor's
        // App.pause / appStateChange:inactive event fires noticeably later —
        // by the time JS receives it, the WKWebView's JS thread has already
        // been throttled for ~100-300ms, producing an audible audio stutter
        // during the swipe-up animation. Hooking this here lets us pause via
        // a direct evaluateJavaScript call before throttling kicks in.
        //
        // We only pause <audio> tags; we do NOT touch the AudioContext or
        // call _markAudioInterrupted here — the existing visibilitychange
        // path in 72-main-late-mid.js handles the suspend + snapshot once
        // Capacitor delivers the app-state event a moment later. Pausing
        // <audio> here twice (here + JS) is harmless: the second .pause()
        // is a no-op since the element is already paused.
        guard let bridgeVC = window?.rootViewController as? CAPBridgeViewController,
              let webView = bridgeVC.webView else { return }
        webView.evaluateJavaScript(
            "document.querySelectorAll('audio').forEach(function(a){ try { if (!a.paused) a.pause(); } catch(_){} });",
            completionHandler: nil
        )
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Re-enable idle timer when backgrounded so we don't drain battery
        application.isIdleTimerDisabled = false
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // ── PRE-ARM (Build 4) ─────────────────────────────────────────────────
        // Reactivate the AVAudioSession BEFORE WKWebView fires visibilitychange,
        // so when JS's resume-gate runs there's an alive native session under it.
        // No JS call here — that happens in applicationDidBecomeActive (which
        // fires shortly after) where the WebView is guaranteed-active and
        // evaluateJavaScript is a trusted-activation context.
        do {
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            // Non-fatal — didBecomeActive's tryNativeResume will retry.
            NSLog("[JetHorizon] willEnterForeground reactivate failed: \(error)")
        }
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Re-disable idle timer when returning to play
        application.isIdleTimerDisabled = true
        // Apply inspector policy once webView exists
        gateWebInspector()
        // Paint the WebView container in the page bg so the home-indicator
        // safe-area gap doesn't show through as a black strip.
        styleWebViewForSafeArea()
        // Register the jhAudio bridge handler once the webView exists.
        registerAudioBridge()
        // Attempt silent audio recovery via the v81 resume-gate. If this is
        // a true cold-launch (no prior backgrounding), audioCtx is undefined
        // or already running — tryNativeResume's fast-path handles both.
        invokeTryNativeResume(reason: "didBecomeActive")
    }

    func applicationWillTerminate(_ application: UIApplication) {
        NotificationCenter.default.removeObserver(self)
    }

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
    }

    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)
    }

}

// ── jhAudio message handler (JS → Swift) ──────────────────────────────────────
// JS posts {action:'rebuildSession'} from src/85-resume-gate.js v81 at the top
// of _nuclearRecover(). Debouncing lives inside rebuildAudioSession itself.
extension AppDelegate: WKScriptMessageHandler {
    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
        guard message.name == AppDelegate.JH_AUDIO_HANDLER_NAME else { return }
        guard let body = message.body as? [String: Any],
              let action = body["action"] as? String else { return }
        switch action {
        case "rebuildSession":
            rebuildAudioSession(reason: "jhAudio.rebuildSession")
        default:
            NSLog("[JetHorizon] jhAudio unknown action: \(action)")
        }
    }
}
